### ISSUE TITLE
Draw Image is limited to array size up to 2x64k = 128k

### ISSUE THREAD

**Issue by Nihonski** [deividAlfa/ST7789-STM32-uGUI#14]
Hi,
thanks alot for the nice app.
Its really fast.
I may report following issues:

    typedef size_t UG_SIZE;
    size_t is onknown to Keil ARM

    I modified lcd.h to ST7789 display with 240x320 pixel.
    All works fine, but Draw Image is limited to array size up to 2x64k = 128k
    240x320 pixel would need array of size 153600.
    When bigger than that, the remaining display area at the bottum shows the image starting from array [0].

    I skipped the ugui_sim.x functions because #include <X11... files are missing in the download.

best regards

**Comment by Nihonski** [comment]
Update on my issues:
- size_t issue is solved

- display with 240x320 pixel (ST7789) :
At the end of LCD_WriteData, the code line  **buff += chunk_size;** should be inserted.
By this way LCD_DrawImage displays the full picture on the full screen 240x320. 
The original fork from Floyd-Fish has the same code.

static void LCD_WriteData(uint8_t *buff, size_t buff_size) {
.........
#endif
    buff += chunk_size;
    buff_size -= chunk_size;
  }
#ifdef LCD_CS
  LCD_PIN(LCD_CS,SET);
#endif
}

However by this modification, the UG_FillScreen / UG_FillFrame function covers only the area of about 240x280. 
40 lines at the bottum are not filled up.
If I write a text line or some small data at the bottum, no problem. The setup in lcd.h of 240x320 pixels works fine.
Possibly there is a bug in the UGUI rather than in Floyd's fork. Sorry I cannot find the rout cause of this problem.
Does the UGUI limit the number of data to 240x280 somewhere?

present workaround:
In addition to above fix (buff += chunk_size;) I use two FillFrame commands instead of one FillScreen.
UG_FillFrame(0, 0, 240, 200, C_WHITE);
UG_FillFrame(0, 200, 240, 320, C_WHITE);
UG_Update();

By above modifications all works fine so far. 
Looking forward to any comments.

best regards

**Comment by deividAlfa** [comment]
You didn't say how you "solved" the issue with `size_t`, it's very likely that you used the wrong integer size like `int` or similar, you should use `unsigned long` or `uint32_t`.

Try adding this to ugui.h and lcd.h:
`#include <stddef.h>`

If still not working, try adding this to ugui.h:
`typedef uint32_t size_t`
